---
name: Update images

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *" # Every day

jobs:
  update_image:
    name: Update image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: telegraf
          - name: backup
          - name: preview-maker
          - name: tools
          - name: s3proxy

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.name }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}
